# Learn Python - 
## Lessons  Numpy 




Numpy Array creation
N-dimensional arrays or ndarray can be created in multiple ways in numpy.

From Python built-in datatypes : lists or tuples

- Using Numpy array creation methods like empty, ,identity ones, ones_like, 
- Using Numpy numeric sequence generators.
- Using Numpy random module.
- By reading data from a file

### Empty and Empty like

empty(shape[, dtype, order])	Return a new array of given shape and type, without initializing entries.

empty_like(a[, dtype, order, subok])	Return a new array with the same shape and type as a given array.

In [51]:
import numpy as np
import os
np.empty(shape=[3,3],dtype= int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [20]:
import numpy as np
np.empty(shape=[2,4]) # create random numbers i observed that a zero array many a times. 

array([[  4.29837112e-322,   3.30035851e-321,   2.47032823e-323,
          2.56753189e-316],
       [  0.00000000e+000,   3.23815565e-319,   2.56783861e-316,
          0.00000000e+000]])

### Identity ,ones and ones_like

identity(n[, dtype])	Return the identity array.

ones(shape[, dtype, order])	Return a new array of given shape and type, filled with ones.

ones_like(a[, dtype, order, subok])	Return an array of ones with the same shape and type as a given array.

In [26]:
idn =np.identity(5)
idn

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [24]:
np.ones_like(a=idn,dtype=np.float16)

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]], dtype=float16)

In [27]:
np.ones([5,2])

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

### Numpy Sequence generators


- arange([start,] stop[, step,][, dtype])	Return evenly spaced values within a given interval.

- linspace(start, stop[, num, endpoint, ...])	Return evenly spaced numbers over a specified interval.
- logspace(start, stop[, num, endpoint, base, ...])	Return numbers spaced evenly on a log scale.



In [33]:
np.arange(start =1 , stop =10, step= 2)

array([1, 3, 5, 7, 9])

In [44]:
np.linspace(start=5 , stop= 25,num=31,endpoint=False,dtype=np.float64)

array([  5.        ,   5.64516129,   6.29032258,   6.93548387,
         7.58064516,   8.22580645,   8.87096774,   9.51612903,
        10.16129032,  10.80645161,  11.4516129 ,  12.09677419,
        12.74193548,  13.38709677,  14.03225806,  14.67741935,
        15.32258065,  15.96774194,  16.61290323,  17.25806452,
        17.90322581,  18.5483871 ,  19.19354839,  19.83870968,
        20.48387097,  21.12903226,  21.77419355,  22.41935484,
        23.06451613,  23.70967742,  24.35483871])

In [48]:
np.logspace(start=1,stop =10, num =5,base =2)

array([    2.        ,     9.51365692,    45.254834  ,   215.2694823 ,
        1024.        ])

### Import from file and string
fromfile(file[, dtype, count, sep])	Construct an array from data in a text or binary file.

fromstring(string[, dtype, count, sep])	A new 1-D array initialized from raw binary or text data in a string.

In [53]:
filename = "temp.txt"
tpath = "."
fpath =os.path.join(tpath,filename)

dt = np.dtype([('time', [('min', int), ('sec', int)]),('temp', float)])
x = np.zeros((1,), dtype=dt)
x['time']['min'] = 10; x['temp'] = 98.25


x.tofile(fpath)


p=np.fromfile(fpath)

p

array([  4.94065646e-323,   9.82500000e+001])

In [56]:
np.fromstring('\x01\x02\x03\x04\x05', dtype=np.uint8, count=3)

array([1, 2, 3], dtype=uint8)

In [57]:
np.fromstring('1 2', dtype=int, sep=' ')



array([1, 2])

### References
https://www.dataquest.io/blog/jupyter-notebook-tips-tricks-shortcuts/

https://blog.dominodatalab.com/lesser-known-ways-of-using-notebooks/
